import type { Metadata } from "next";
import Navigator from "@/components/navigator";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full min-h-screen h-full flex flex-col gap-1">
      {children}
    </main> 
  );
}
